stages:
  - test

test-ansible:
  stage: test
  image: quay.io/ansible/creator-ee:v0.5.0
  script:
    - chmod -R 755 ../
    - export ANSIBLE_CONFIG=ansible.cfg
    - ansible --version
    # yaml linter
    - find ./ -type f -name "*.yml" -exec yamllint -f colored {} \;
    # ansible linter
    - ansible-lint --force-color -p
    # Syntax check
    # - >
    #     for i in $(ls ./ | grep yml); do
    #       ansible-playbook $i --syntax-check
    #     done
  tags:
    - docker-on-runner

# stages:
#   - test

# image: docker:stable-dind

# services:
#   - docker:dind

# before_script:
#   - apk add --no-cache
#     python3 python3-dev py3-pip gcc git curl build-base
#     autoconf automake py3-cryptography linux-headers
#     musl-dev libffi-dev openssl-dev openssh
#   - docker info
#   - python3 --version
#   - python3 -m pip install ansible molecule[docker] ansible-lint
#   - ansible --version
#   - molecule --version

# molecule:
#   stage: test
#   script:
#     - cd roles/nfs-server
#     - molecule test
#   tags:
#     - docker-on-runner
