- name: user-setup | Create ansible user
  ansible.builtin.user:
    name: "{{ instance_ssh_user }}"
    comment: "User created for ansible"
  tags: host-provision

- name: user-setup | Slurp public key contents 
  ansible.builtin.slurp:
    src: "{{ control_node_key_file }}.pub"
  register: public_key_content_scrambled
  delegate_to: localhost
  connection: local
  become: no
  tags: host-provision

- name: user-setup | Store public key contents to be transferred from control node to hosts
  ansible.builtin.set_fact:
    public_key_content: "{{ public_key_content_scrambled['content'] | b64decode  }}"
  tags: host-provision

- name: user-setup | Transfer public key from control node to hosts
  ansible.builtin.authorized_key:
    user: "{{ instance_ssh_user }}"
    state: present
    key: "{{ public_key_content }}"
  tags: host-provision

- name: user-setup | Add sudoers file for ansible
  ansible.builtin.template:
    src: hostprovision_ansible_user.j2
    dest: "/etc/sudoers.d/{{ instance_ssh_user }}"
  tags: host-provision

